language: c
sudo: true
dist: trusty
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION="6.9"
    - RACKET_VERSION="HEAD"
matrix:
  allow_failures:
    - env: RACKET_VERSION="HEAD"

before_install:
  # libmlt6
  - sudo apt-get -qq update
  - sudo apt-get install -y libmlt6
  - sudo apt-get install -y libav-tools
#  - sudo apt-get install -y ffmpeg
  - sudo apt-get install -y ladspa-sdk
  - sudo apt-get install -y libgdk-pixbuf2.0-*
  - sudo apt-get install -y frei0r-plugins*
  - sudo apt-get install libdc1394-*
  # Turn off the irrelevant libdc1394 warning
  - sudo ln /dev/null /dev/raw1394
  # racket
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  # enable gtk
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  # install (untyped) racket-video
  - git clone https://github.com/stchang/racket-video.git ../video
  - raco pkg install --auto -n video ../video
  # install turnstile
  - git clone --branch v0.1 https://github.com/stchang/macrotypes.git
  - raco pkg install --auto -n turnstile macrotypes/
  
install:
 - raco pkg install --auto

script:
 - raco test --package typed-video
 - raco setup